name: Test Python Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Python container
      run: |
        docker run python:3.9-slim python -c "print('Hello from Docker!')"
